# Generated by Django 2.2.11 on 2020-04-04 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='period',
            old_name='agreement',
            new_name='related_agreement',
        ),
    ]
