# Generated by Django 2.2.11 on 2020-04-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0007_auto_20200405_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='start_date',
            field=models.DateField(verbose_name='date of the start'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='stop_date',
            field=models.DateField(verbose_name='date of the stop'),
        ),
        migrations.AlterField(
            model_name='period',
            name='start_date',
            field=models.DateField(verbose_name='date of the start'),
        ),
        migrations.AlterField(
            model_name='period',
            name='stop_date',
            field=models.DateField(verbose_name='date of the stop'),
        ),
    ]
